PUT http://localhost:3000/api/user/validation
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjdkYmVhYjliYzViMTE0ODY0NDRmMTRlIiwiZW1haWwiOiJlbWFpbF8xQGVqZW1wbG8uY29tIiwicm9sZSI6InVzZXIifSwiaWF0IjoxNzQyNDY1NzIxLCJleHAiOjE3NDI1NTIxMjF9.clQiCUibj5P2G1HnKXifA6nPjgyP5TzRDcOtAGt2624
{
    "code": "829279"
}
